import "../globals.css";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Auth",
  description: "Generated by create next app",
};
const AuthLayout = ({ 
    children
  }) => {
    return ( 
      <html lang='en'>
        <body className={inter.className}>
        <div className="h-screen flex items-center justify-center bg-gradient-to-tr from-[#002B5B] via-[#004E89] to-[#00B4D8]">
        { children }
      </div>
      </body>
      </html>
     );
  }
   
  export default AuthLayout;